import type { BrushPreset } from '../types';

export const defaultBrushPresets: BrushPreset[] = [
  // Basic Brushes
  {
    id: 'hard-round',
    name: 'Hard Round',
    type: 'round',
    size: 20,
    hardness: 100,
    opacity: 100,
    flow: 100,
    spacing: 25,
    angle: 0,
    roundness: 100,
    scattering: 0,
    pressureSensitivity: {
      size: true,
      opacity: false,
      hardness: false,
      flow: false,
    },
  },
  {
    id: 'soft-round',
    name: 'Soft Round',
    type: 'soft',
    size: 50,
    hardness: 0,
    opacity: 100,
    flow: 50,
    spacing: 10,
    angle: 0,
    roundness: 100,
    scattering: 0,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: false,
      flow: false,
    },
  },
  {
    id: 'soft-round-pressure',
    name: 'Soft Round Pressure Opacity',
    type: 'soft',
    size: 45,
    hardness: 0,
    opacity: 100,
    flow: 100,
    spacing: 10,
    angle: 0,
    roundness: 100,
    scattering: 0,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: false,
      flow: true,
    },
  },

  // Artistic Brushes
  {
    id: 'airbrush-soft',
    name: 'Airbrush Soft',
    type: 'airbrush',
    size: 100,
    hardness: 0,
    opacity: 20,
    flow: 10,
    spacing: 5,
    angle: 0,
    roundness: 100,
    scattering: 0,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: false,
      flow: true,
    },
  },
  {
    id: 'airbrush-pen',
    name: 'Airbrush Pen',
    type: 'airbrush',
    size: 30,
    hardness: 0,
    opacity: 30,
    flow: 20,
    spacing: 5,
    angle: 0,
    roundness: 100,
    scattering: 0,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: false,
      flow: true,
    },
  },

  // Pencils
  {
    id: 'pencil-hard',
    name: 'Hard Pencil',
    type: 'pencil',
    size: 3,
    hardness: 100,
    opacity: 100,
    flow: 100,
    spacing: 15,
    angle: 45,
    roundness: 80,
    scattering: 5,
    pressureSensitivity: {
      size: true,
      opacity: false,
      hardness: false,
      flow: false,
    },
  },
  {
    id: 'pencil-soft',
    name: 'Soft Pencil',
    type: 'pencil',
    size: 5,
    hardness: 70,
    opacity: 80,
    flow: 100,
    spacing: 10,
    angle: 35,
    roundness: 70,
    scattering: 10,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: true,
      flow: false,
    },
  },
  {
    id: 'pencil-sketch',
    name: 'Sketch Pencil',
    type: 'pencil',
    size: 8,
    hardness: 50,
    opacity: 60,
    flow: 80,
    spacing: 8,
    angle: 45,
    roundness: 60,
    scattering: 15,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: true,
      flow: true,
    },
  },

  // Markers
  {
    id: 'marker-round',
    name: 'Round Marker',
    type: 'marker',
    size: 20,
    hardness: 100,
    opacity: 100,
    flow: 100,
    spacing: 5,
    angle: 0,
    roundness: 100,
    scattering: 0,
    pressureSensitivity: {
      size: false,
      opacity: false,
      hardness: false,
      flow: false,
    },
  },
  {
    id: 'marker-flat',
    name: 'Flat Marker',
    type: 'flat',
    size: 30,
    hardness: 100,
    opacity: 100,
    flow: 100,
    spacing: 10,
    angle: 45,
    roundness: 30,
    scattering: 0,
    pressureSensitivity: {
      size: false,
      opacity: false,
      hardness: false,
      flow: false,
    },
  },
  {
    id: 'marker-chisel',
    name: 'Chisel Marker',
    type: 'flat',
    size: 25,
    hardness: 90,
    opacity: 90,
    flow: 100,
    spacing: 8,
    angle: 30,
    roundness: 20,
    scattering: 0,
    pressureSensitivity: {
      size: true,
      opacity: false,
      hardness: false,
      flow: false,
    },
  },

  // Painting Brushes
  {
    id: 'oil-flat',
    name: 'Oil Flat',
    type: 'flat',
    size: 40,
    hardness: 80,
    opacity: 80,
    flow: 70,
    spacing: 15,
    angle: 0,
    roundness: 40,
    scattering: 5,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: false,
      flow: true,
    },
  },
  {
    id: 'watercolor-wet',
    name: 'Watercolor Wet',
    type: 'soft',
    size: 60,
    hardness: 0,
    opacity: 30,
    flow: 20,
    spacing: 5,
    angle: 0,
    roundness: 100,
    scattering: 20,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: false,
      flow: true,
    },
  },
  {
    id: 'acrylic-round',
    name: 'Acrylic Round',
    type: 'round',
    size: 35,
    hardness: 60,
    opacity: 90,
    flow: 85,
    spacing: 20,
    angle: 0,
    roundness: 100,
    scattering: 3,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: true,
      flow: true,
    },
  },

  // Special Brushes
  {
    id: 'scatter-dots',
    name: 'Scatter Dots',
    type: 'round',
    size: 15,
    hardness: 100,
    opacity: 100,
    flow: 100,
    spacing: 100,
    angle: 0,
    roundness: 100,
    scattering: 80,
    pressureSensitivity: {
      size: true,
      opacity: false,
      hardness: false,
      flow: false,
    },
  },
  {
    id: 'spray-paint',
    name: 'Spray Paint',
    type: 'airbrush',
    size: 80,
    hardness: 0,
    opacity: 15,
    flow: 5,
    spacing: 3,
    angle: 0,
    roundness: 100,
    scattering: 50,
    pressureSensitivity: {
      size: false,
      opacity: true,
      hardness: false,
      flow: true,
    },
  },
  {
    id: 'chalk',
    name: 'Chalk',
    type: 'textured',
    size: 25,
    hardness: 50,
    opacity: 70,
    flow: 80,
    spacing: 15,
    angle: 0,
    roundness: 80,
    scattering: 25,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: false,
      flow: false,
    },
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    type: 'textured',
    size: 30,
    hardness: 30,
    opacity: 60,
    flow: 70,
    spacing: 10,
    angle: 45,
    roundness: 50,
    scattering: 30,
    pressureSensitivity: {
      size: true,
      opacity: true,
      hardness: true,
      flow: true,
    },
  },
];

// Brush categories for UI organization
export const brushCategories = [
  {
    id: 'basic',
    name: 'Basic Brushes',
    presets: ['hard-round', 'soft-round', 'soft-round-pressure'],
  },
  {
    id: 'airbrush',
    name: 'Airbrush',
    presets: ['airbrush-soft', 'airbrush-pen'],
  },
  {
    id: 'pencils',
    name: 'Pencils',
    presets: ['pencil-hard', 'pencil-soft', 'pencil-sketch'],
  },
  {
    id: 'markers',
    name: 'Markers',
    presets: ['marker-round', 'marker-flat', 'marker-chisel'],
  },
  {
    id: 'painting',
    name: 'Painting',
    presets: ['oil-flat', 'watercolor-wet', 'acrylic-round'],
  },
  {
    id: 'special',
    name: 'Special',
    presets: ['scatter-dots', 'spray-paint', 'chalk', 'charcoal'],
  },
];

// Get a brush preset by ID
export function getBrushPreset(id: string): BrushPreset | undefined {
  return defaultBrushPresets.find(preset => preset.id === id);
}

// Get brushes for a category
export function getBrushesForCategory(categoryId: string): BrushPreset[] {
  const category = brushCategories.find(c => c.id === categoryId);
  if (!category) return [];
  return category.presets
    .map(id => getBrushPreset(id))
    .filter((p): p is BrushPreset => p !== undefined);
}

// Create a custom brush based on an existing preset
export function createCustomBrush(basedOn: BrushPreset, overrides: Partial<BrushPreset>): BrushPreset {
  return {
    ...basedOn,
    ...overrides,
    id: `custom-${Date.now()}`,
    isCustom: true,
  };
}
